services:
  db:
    image: postgres:14
    restart: always
    container_name: watch_party_pg
    environment:
      POSTGRES_USER: watch_party_user
      POSTGRES_PASSWORD: super_secret_password
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./pg_scripts:/pg_scripts:ro # init and migration scripts
